# Generated by Django 6.0.6 on 2026-06-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.IntegerField(default=0, help_text='Biometric device communication password (Comkey), default is 0.'),
        ),
    ]
