# Generated by Django 6.0.6 on 2026-06-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('devices', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_corrections', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='attendancecorrectionrequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='devices.device'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='employees.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancelog',
            unique_together={('employee', 'timestamp')},
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('employee', 'date')},
        ),
    ]
