# Generated by Django 6.0.6 on 2026-06-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_update_shift_durations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='punch_type',
            field=models.CharField(choices=[('CHECK_IN', 'Check In'), ('CHECK_OUT', 'Check Out'), ('BREAK_IN', 'Break In'), ('BREAK_OUT', 'Break Out'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
    ]
